branches:
  only:
    - master

skip_tags: true
max_jobs: 1

image: 
  - Visual Studio 2017

install:
  - C:\Python37-x64\python -m pip install -r requirements.txt
  - C:\Python37-x64\python -m pip install -U pytest pytest-cov flake8 pylint codecov sphinx apache-airflow luigi python-crontab mock matplotlib pyEX pandas seaborn pytest-falcon

environment:
  matrix:
    - AIRFLOW_GPL_UNIDECODE: 1

cache:
  - '%LOCALAPPDATA%\pip\Cache'

build_script:
  - C:\Python37-x64\python setup.py build

test_script:
  - C:\Python37-x64\python -m pytest -v tests --cov=paperboy
