language: python
cache: pip

python:
  - "3.6"

env:
  - AIRFLOW_GPL_UNIDECODE=1

install:
    - pip install -r requirements.txt
    - pip install .[test]
    - pip install .[docs]
    - pip install -U apache-airflow luigi python-crontab matplotlib pyEX pandas seaborn
    - yarn

script:
  - make test
  - make docs

after_success:
    - codecov --token 35952f9c-a1a5-4d77-ba0c-d91e6f24dfec

branches:
  only:
  - master

notifications:
  email: false
