language: python
cache: pip

python:
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - AIRFLOW_GPL_UNIDECODE=1

install:
    - pip install .[dev]
    - pip install -U apache-airflow luigi python-crontab matplotlib pyEX pandas seaborn
    - yarn

script: make test

after_success:
    - codecov --token 35952f9c-a1a5-4d77-ba0c-d91e6f24dfec

branches:
  only:
  - master

notifications:
  email: false
